app = "whitepaper-ai"
primary_region = "ams"

[build]
  image = "python:3.9"
  command = """
    pip install -r requirements.txt
  """

[env]
  AZURE_AI_MODEL_NAME = "Meta-Llama-3.1-405B-Instruct"
  DEVELOPMENT = "false"
  VITE_API_BASE_URL = "https://whitepaper-ai.fly.dev"

[[services]]
  internal_port = 10000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443